import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Poppins,
  Bricolage_Grotesque,
} from "next/font/google";
import "./globals.css";
import { ToastHost } from "./components/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-chubbo",
  weight: ["200", "400", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${bricolage.variable} antialiased snap-container`}
      >
        {children}
        {/* Toasts */}
        <ToastHost />
      </body>
    </html>
  );
}
